includes:
  - secret.yaml

runtime: java11
entrypoint: 'java -Xmx80m -jar *.jar'

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_instances: 2

