includes:
  - secret.yaml

runtime: java11
entrypoint: 'java -Xmx32m -jar *.jar'

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

