name: merge

on:
  push:
    paths:
      - '**.kt'
      - '.github/workflows/merge.yaml'
      - '**.gradle'
      - 'resources/**'
      - 'gradle/**'
      - 'system.properties'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: set firebase
      run: npm install -g firebase-tools

    - name: build
      run: firebase emulators:exec "./gradlew clean check" --only firestore

    - name: Test Report
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: build/reports/tests/test

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,action,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()